# version: '3'
services:
  node-server:
    build:
      context: ./
      dockerfile: Dockerfile_server
      args:
        - USER_UID=${UID}
        - USER_GID=${GID}
    user: "${UID}:${GID}"
    container_name: node
    volumes:
      - ./packages/backend:/packages/backend
    environment:
      USER_UID: ${UID}
      USER_GID: ${GID}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8000:8000"
    tty: true

  redis:
    image: redis:8.0-bookworm
    container_name: redis
    ports:
      - "6379:6379"