# version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_UID=${UID}
        - USER_GID=${GID}
    user: "${UID}:${GID}"
    container_name: node-backend
    volumes:
      - ./packages/backend:/node-app/backend
    environment:
      USER_UID: ${UID}
      USER_GID: ${GID}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8000:8000"
    tty: true

  redis:
    image: redis:8.0-bookworm
    container_name: redis
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/data